###
GET http://localhost:3001/pets

###
POST http://localhost:3001/pets/new
Content-Type: application/json

{
    "petName" : "Lemniscate",
    "petDescription" : "A cuddly little noodle! So pretty and lovely <3" 
}

###
GET http://localhost:3001/pets/64c78bfaafde0258b4364312

###
GET http://localhost:3001/feed

###
POST http://localhost:3001/feed/new
Content-Type: application/json

{
    "feedName" : "85g rat",
    "portionsLeft" : 20
}

###
DELETE http://localhost:3001/pets/delete/64d5360aecf1677cf6f497a5

###
GET http://localhost:3001/feedingEvents/

###
POST http://localhost:3001/feedingEvents/new/
Content-Type: application/json

{
    "petId" : "64de1571d6ba6d3aa1c84a1c",
    "feedId" : "64de157fd6ba6d3aa1c84a20",
    "portionsFed" : 2,
    "feedingEventDescription" : "A brand new feeding for a freshly shed snake! And again!"
}

###
GET http://localhost:3001/pets/feedingEvents