###
GET http://localhost:3001/pets

###
POST http://localhost:3001/pets/new
Content-Type: application/json

{
    "petName" : "Lemniscate",
    "petDescription" : "A cuddly little noodle! So pretty and lovely <3" 
}

###
GET http://localhost:3001/pets/64de1571d6ba6d3aa1c84a1c

###
GET http://localhost:3001/feed

###
POST http://localhost:3001/feed/new
Content-Type: application/json

{
    "feedName" : "120g rat",
    "portionsLeft" : 10
}

###
DELETE http://localhost:3001/pets/delete/64d5360aecf1677cf6f497a5

###
GET http://localhost:3001/feedingEvents/

###
POST http://localhost:3001/feedingEvents/new/
Content-Type: application/json

{
    "petId" : "64de1571d6ba6d3aa1c84a1c",
    "feedId" : "64e4704cf274757a86323b00",
    "portionsFed" : 5,
    "feedingEventDescription" : "A new feeding!"
}

###
GET http://localhost:3001/pets/feedingEvents
Content-Type: application/json

{
    "petId" : "64de1571d6ba6d3aa1c84a1c"
}

###
DELETE http://localhost:3001/feedingEvents/deleteByPetId
Content-Type: application/json

{
    "petId" : "64de1571d6ba6d3aa1c84a1c"
}